freebsd_instance:
  image_family: freebsd-14-0

task:
  install_script: pkg install -y cmake
  build_script: |
    mkdir -p build && cd build
    cmake -DENABLE_NETIF_TESTS=ON ..
    make
    ctest --verbose
    ifconfig
