jobs:
- job: Native
  strategy:
    matrix:
      Linux:
        imageName: "ubuntu-16.04"
      macOS:
        imageName: "macos-10.14"
      Windows:
        imageName: "windows-2019"
  pool:
    vmImage: $(imageName)

  steps:
  - script: |
      echo "All 3 Azure platforms will run this"
    displayName: 'Run on Linux/macOS/Windows'

  # Linux only
  - bash: |
      echo "This is only run on Linux"
      echo "Dependencies could be installed with apt-get"
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: 'Run on Linux'

  # macOS only
  - bash: |
      echo "This is only run on macOS"
      echo "Dependencies could be installed with homebrew"
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: 'Run on macOS'

  # Windows only
  - bash: |
      echo "This is only run on Windows"
      echo "Dependencies could be installed with choco"
    displayName: 'Run on Windows'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
